version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=storaHalloweenPumpor
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'

  gr-films:
    container_name: gr-films-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/movies
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=storaHalloweenPumpor
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
